# These are the official GitHub Sponsors handles
github: [Shannon-Goddard]

# This adds a link to your external app/website
custom: ["https://www.loyal9.app/tools/contact-us/contact-us.html", "https://growappcannabis.guide/tools/contact-us/contact-us.html"]
